# Generated by Django 4.2.3 on 2023-10-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_no', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.IntegerField(default=100)),
                ('Quantity', models.IntegerField(default=1)),
                ('Description', models.TextField()),
                ('Arrival_Date', models.DateField(auto_now_add=True)),
                ('Manufactured_Date', models.DateField(null=True)),
                ('Expiry_Date', models.DateField(null=True)),
                ('Brand', models.CharField(max_length=200, null=True)),
                ('Distributor', models.CharField(max_length=200)),
                ('Condition', models.CharField(choices=[('spoilt', 'spoilt'), ('Good', 'Good')], default='Good', max_length=200)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.category')),
                ('Shelf_No', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.shelf')),
            ],
        ),
    ]
