# Generated by Django 4.2.3 on 2023-10-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
